name: Build

on:
  push:
    tags:
      - v1.**
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        sdk:
          - openwrt-24.10
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: SunHHB/gh-action-sdk@go1.24
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-tailscale
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Create compress files
        run: |
          tar -zcvf luci-app-tailscale_${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/ packages_ci .

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "luci-app-tailscale_${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz"

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 2  
          delete_tags: true
          
      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2
